export default defineEventHandler((event) => {
  return [
    {
      name: 'description',
      position: 1,
      width: '300',
      isVisible: true,
      isClickable: false,
      clickAction: null,
      clickValue: null,
      subColumns: [],
    },
    {
      name: 'note',
      position: 2,
      width: '300',
      isVisible: true,
      isClickable: false,
      clickAction: null,
      clickValue: null,
      subColumns: [],
    },
    {
      name: 'colt',
      position: 3,
      width: '100',
      isVisible: true,
      isClickable: true,
      clickAction: 'url',
      clickValue: 'https://google.be/search?q=',
      subColumns: [],
    },
    {
      name: 'shift',
      position: 0,
      width: '170',
      isVisible: true,
      isClickable: false,
      clickAction: null,
      clickValue: null,
      subColumns: [
        { name: 'week', width: '33' },
        { name: 'date', width: '33' },
        { name: 'schedule', width: '34' },
      ],
    },
    {
      name: 'status',
      position: 4,
      width: '100',
      isVisible: true,
      isClickable: false,
      clickAction: null,
      clickValue: null,
      subColumns: [],
    },
    {
      name: 'limit',
      position: 5,
      width: '600',
      isVisible: true,
      isClickable: false,
      clickAction: null,
      clickValue: null,
      subColumns: [
        { name: 'fromLine', width: '5' },
        { name: 'fromStation', width: '20' },
        { name: 'fromLane', width: '5' },
        { name: 'fromSignal', width: '10' },
        { name: 'fromPK', width: '10' },
        { name: 'toLine', width: '5' },
        { name: 'toStation', width: '20' },
        { name: 'toLane', width: '5' },
        { name: 'toSignal', width: '10' },
        { name: 'toPK', width: '10' },
      ],
    },
    {
      name: 'wielding',
      position: 6,
      width: '100',
      isVisible: true,
      isClickable: false,
      clickAction: null,
      clickValue: null,
      subColumns: [],
    },
    {
      name: 'supervisor',
      position: 7,
      width: '100',
      isVisible: true,
      isClickable: false,
      clickAction: null,
      clickValue: null,
      subColumns: [],
    },
  ]
})
