export default defineEventHandler((event) => {
  return [
    {
      name: 'description',
      position: 1,
      width: '300',
      isVisible: true,
      isMultiple: true,
      isClickable: false,
      clickAction: null,
      clickValue: null,
      subColumns: [],
    },
    {
      name: 'note',
      position: 2,
      width: '300',
      isVisible: true,
      isMultiple: false,
      isClickable: false,
      clickAction: null,
      clickValue: null,
      subColumns: [],
    },
    {
      name: 'colt',
      position: 3,
      width: '100',
      isVisible: true,
      isMultiple: false,
      isClickable: true,
      clickAction: 'url',
      clickValue: 'https://google.be/search?q=',
      subColumns: [],
    },
    {
      name: 'shift',
      position: 0,
      width: '170',
      isVisible: true,
      isMultiple: true,
      isClickable: false,
      clickAction: null,
      clickValue: null,
      subColumns: [
        { name: 'week', width: '33' },
        { name: 'date', width: '33' },
        { name: 'schedule', width: '34' },
      ],
    },
  ]
})
